import { test } from 'node:test';
import assert from 'node:assert/strict';
import { comparerVersions, controler, lirePubspecLock, versionTouchee } from '../avis_dart.mjs';

const LOCK = `# Generated by pub
packages:
  async:
    dependency: transitive
    description:
      name: async
      sha256: "abc"
      url: "https://pub.dev"
    source: hosted
    version: "2.13.0"
  dio:
    dependency: "direct main"
    description:
      name: dio
      sha256: "def"
      url: "https://pub.dev"
    source: hosted
    version: "5.11.1"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  mon_paquet_git:
    dependency: "direct main"
    description:
      path: "."
      ref: main
      url: "https://example.com/depot.git"
    source: git
    version: "1.0.0"
  autre_depot:
    dependency: transitive
    description:
      name: autre_depot
      url: "https://depot.exemple.com"
    source: hosted
    version: "3.0.0"
  cross_file:
    dependency: transitive
    description:
      name: cross_file
      url: "https://pub.dev"
    source: hosted
    version: "0.3.5+5"
sdks:
  dart: ">=3.13.0 <4.0.0"
`;

const avisDio = {
  id: 'GHSA-test-dio',
  summary: 'dio : injection CRLF',
  affected: [{ ranges: [{ type: 'ECOSYSTEM', events: [{ introduced: '0' }, { fixed: '5.0.0' }] }], versions: ['4.0.0'] }],
};

test('pubspec.lock : seuls les paquets hébergés sur pub.dev sont retenus', () => {
  assert.deepEqual(lirePubspecLock(LOCK), [
    { nom: 'async', version: '2.13.0' },
    { nom: 'dio', version: '5.11.1' },
    { nom: 'cross_file', version: '0.3.5+5' },
  ]);
});

test('ordre des versions façon pub_semver', () => {
  const avant = (a, b) => assert.equal(comparerVersions(a, b), -1, `${a} < ${b}`);
  avant('1.0.0', '1.0.1');
  avant('1.9.9', '1.10.0');
  avant('1.0.0-beta', '1.0.0');
  avant('1.0.0-beta.2', '1.0.0-beta.10');
  avant('1.0.0-alpha', '1.0.0-beta');
  avant('1.0.0', '1.0.0+1');
  avant('0.3.5', '0.3.5+5');
  assert.equal(comparerVersions('2.0.0', '2.0.0'), 0);
  assert.equal(comparerVersions('5.0.0', '4.9.9'), 1);
});

test('version touchée : plages OSV, bornes et liste explicite', () => {
  assert.equal(versionTouchee('4.9.9', avisDio), true);
  assert.equal(versionTouchee('0.0.1', avisDio), true);
  assert.equal(versionTouchee('5.0.0', avisDio), false, 'la version corrigée n\'est plus touchée');
  assert.equal(versionTouchee('5.11.1', avisDio), false);

  const dernier = { affected: [{ ranges: [{ type: 'ECOSYSTEM', events: [{ introduced: '1.2.0' }, { last_affected: '1.4.0' }] }] }] };
  assert.equal(versionTouchee('1.1.9', dernier), false);
  assert.equal(versionTouchee('1.2.0', dernier), true);
  assert.equal(versionTouchee('1.4.0', dernier), true);
  assert.equal(versionTouchee('1.4.1', dernier), false);

  const deuxPlages = {
    affected: [{ ranges: [{ type: 'ECOSYSTEM', events: [{ introduced: '0' }, { fixed: '1.0.0' }, { introduced: '2.0.0' }, { fixed: '2.0.5' }] }] }],
  };
  assert.equal(versionTouchee('0.5.0', deuxPlages), true);
  assert.equal(versionTouchee('1.5.0', deuxPlages), false);
  assert.equal(versionTouchee('2.0.3', deuxPlages), true);
  assert.equal(versionTouchee('2.0.5', deuxPlages), false);

  assert.equal(versionTouchee('9.9.9', { affected: [{ versions: ['9.9.9'] }] }), true);
  assert.equal(versionTouchee('1.0.0', {}), false);
});

const reponse = (advisories, ok = true) => ({ ok, status: ok ? 200 : 500, json: async () => ({ advisories }) });
const fetcherDe = (parPaquet) => async (url) => {
  const nom = decodeURIComponent(/packages\/([^/]+)\/advisories/.exec(url)[1]);
  if (parPaquet[nom] instanceof Error) throw parPaquet[nom];
  return reponse(parPaquet[nom] ?? []);
};
const aujourdhui = new Date('2026-10-08T12:00:00Z');

test('contrôle : un avis qui touche la version verrouillée bloque, les autres non', async () => {
  const fetcher = fetcherDe({ dio: [avisDio] });
  const sain = await controler([{ nom: 'dio', version: '5.11.1' }, { nom: 'async', version: '2.13.0' }], { fetcher, aujourdhui });
  assert.equal(sain.controles, 2);
  assert.deepEqual(sain.bloquants, []);

  const touche = await controler([{ nom: 'dio', version: '4.0.0' }], { fetcher, aujourdhui });
  assert.equal(touche.bloquants.length, 1);
  assert.equal(touche.bloquants[0].id, 'GHSA-test-dio');
  assert.equal(touche.bloquants[0].version, '4.0.0');
});

test('exceptions : valable = toléré ; échue, sans motif ou autre projet = bloque', async () => {
  const fetcher = fetcherDe({ dio: [avisDio] });
  const paquets = [{ nom: 'dio', version: '4.0.0' }];
  const exception = (extra = {}) => ({
    avis: 'GHSA-test-dio', projet: 'dart', raison: 'Fonction jamais appelée par l\'app (vérifié).', jusqu_au: '2026-12-31', ...extra,
  });

  const toleree = await controler(paquets, { fetcher, aujourdhui, exceptions: [exception()] });
  assert.equal(toleree.bloquants.length, 0);
  assert.equal(toleree.toleres.length, 1);

  const echue = await controler(paquets, { fetcher, aujourdhui, exceptions: [exception({ jusqu_au: '2026-10-07' })] });
  assert.equal(echue.bloquants.length, 1);
  assert.equal(echue.echues.length, 1);

  const sansMotif = await controler(paquets, { fetcher, aujourdhui, exceptions: [exception({ raison: 'ok' })] });
  assert.equal(sansMotif.bloquants.length, 1);

  const autreProjet = await controler(paquets, { fetcher, aujourdhui, exceptions: [exception({ projet: 'functions' })] });
  assert.equal(autreProjet.bloquants.length, 1);

  const joker = await controler(paquets, { fetcher, aujourdhui, exceptions: [exception({ projet: '*' })] });
  assert.equal(joker.bloquants.length, 0);
});

test('base injoignable : signalé, jamais pris pour « aucun avis »', async () => {
  const fetcher = fetcherDe({ dio: new Error('réseau coupé'), async: [] });
  const bilan = await controler([{ nom: 'dio', version: '5.11.1' }, { nom: 'async', version: '2.13.0' }], { fetcher, aujourdhui });
  assert.deepEqual(bilan.injoignables, ['dio']);
  assert.deepEqual(bilan.bloquants, []);
});

test('avis retiré (withdrawn) : ignoré', async () => {
  const fetcher = fetcherDe({ dio: [{ ...avisDio, withdrawn: '2024-01-01T00:00:00Z' }] });
  const bilan = await controler([{ nom: 'dio', version: '4.0.0' }], { fetcher, aujourdhui });
  assert.deepEqual(bilan.bloquants, []);
});
